#ifndef _DEBUG_CONFIG_H_
#define _DEBUG_CONFIG_H_

#include <SerialPrintf.h>

// Override which can be used to disable all zones
#define DEBUG_MASTER                        1

#define DEBUG_CONTROLLER                    (1 && DEBUG_MASTER)
#define DEBUG_NODE                          (1 && DEBUG_MASTER)
#define DEBUG_G35                           (0 && DEBUG_MASTER)
#define DEBUG_SEND_COMMAND                  (0 && DEBUG_MASTER)
#define DEBUG_CONFIG                        (1 && DEBUG_MASTER)


#define DEBUG_LIGHT_PROGRAM_TEST            (0 && DEBUG_MASTER)
#define DEBUG_SEQUENCE_UTILS                (0 && DEBUG_MASTER)
#define DEBUG_WAVE_UTILS                    (0 && DEBUG_MASTER)
#define DEBUG_COLOR_UTILS                   (0 && DEBUG_MASTER)
#define DEBUG_PROGRAM_RUNNER                (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM                 (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_CHASE           (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_CREEPERS        (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_CYLON           (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_DISSOLVE        (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_DRIP_FILL       (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_EYES            (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_INCHWORM        (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_MEOCHASING      (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_MEOCOLORPHASING (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_MEODITHER       (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_MEOOSCILLATE    (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_MEORANDOMSTROBE (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_MEOSIMPLEXNOISE (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_MEOSINEWAVE     (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_MEOSWITCHOFF    (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_MEOWHITES       (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_METEORITE       (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_ORBIT           (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_PULSE           (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_PUMPKINCHASE    (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_RAINBOW         (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_RAW             (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_REDGREENCHASE   (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_RANDOM_FADE     (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_SHOOTING_STARS  (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_SNOWFLAKE       (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_SOLID           (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_SPOOKY_EYES     (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_SPOOKYFLICKER   (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_SPOOKYSLOW      (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_STAR            (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_STEREO          (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_STOCK           (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_STROBE_FILL     (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_TWINKLE         (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_WAVE            (0 && DEBUG_MASTER)


#define DEBUG_LIGHT_PROGRAM_CONTROLLER_HOLLY            (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_CONTROLLER_ICE              (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_CONTROLLER_CANDY_CANE       (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_CONTROLLER_DISSOLVE         (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_CONTROLLER_SOLID_RAINBOW    (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_CONTROLLER_METEORITE        (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_CONTROLLER_TWINKLE          (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_CONTROLLER_CHASE            (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_CONTROLLER_STROBE           (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_CONTROLLER_RAINBOW_STROBE   (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_CONTROLLER_RAINBOW_CHASE    (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_CONTROLLER_FADEIN_FADEOUT   (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_CONTROLLER_ALTERNATE_DIRECTION  (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_CONTROLLER_SPIRAL_STARS     (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_CONTROLLER_STEPPED_WAVE     (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_CONTROLLER_STROBE_FILL      (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_CONTROLLER_UW               (0 && DEBUG_MASTER)
#define DEBUG_LIGHT_PROGRAM_CONTROLLER_SEAHAWKS         (0 && DEBUG_MASTER)



#define DEBUG_NODE_ANY  (                           \
    DEBUG_NODE                                  ||  \
    DEBUG_CONFIG                                ||  \
    DEBUG_SEQUENCE_UTILS                        ||  \
    DEBUG_PROGRAM_RUNNER                        ||  \
    DEBUG_LIGHT_PROGRAM_TEST                    ||  \
    DEBUG_LIGHT_PROGRAM                         ||  \
    DEBUG_LIGHT_PROGRAM_CHASE                   ||  \
    DEBUG_LIGHT_PROGRAM_CREEPERS                ||  \
    DEBUG_LIGHT_PROGRAM_CYLON                   ||  \
    DEBUG_LIGHT_PROGRAM_DISSOLVE                ||  \
    DEBUG_LIGHT_PROGRAM_DRIP_FILL               ||  \
    DEBUG_LIGHT_PROGRAM_EYES                    ||  \
    DEBUG_LIGHT_PROGRAM_INCHWORM                ||  \
    DEBUG_LIGHT_PROGRAM_MEOCHASING              ||  \
    DEBUG_LIGHT_PROGRAM_MEOCOLORPHASING         ||  \
    DEBUG_LIGHT_PROGRAM_MEODITHER               ||  \
    DEBUG_LIGHT_PROGRAM_MEOOSCILLATE            ||  \
    DEBUG_LIGHT_PROGRAM_MEORANDOMSTROBE         ||  \
    DEBUG_LIGHT_PROGRAM_MEOSIMPLEXNOISE         ||  \
    DEBUG_LIGHT_PROGRAM_MEOSINEWAVE             ||  \
    DEBUG_LIGHT_PROGRAM_MEOSWITCHOFF            ||  \
    DEBUG_LIGHT_PROGRAM_MEOWHITES               ||  \
    DEBUG_LIGHT_PROGRAM_METEORITE               ||  \
    DEBUG_LIGHT_PROGRAM_ORBIT                   ||  \
    DEBUG_LIGHT_PROGRAM_PULSE                   ||  \
    DEBUG_LIGHT_PROGRAM_PUMPKINCHASE            ||  \
    DEBUG_LIGHT_PROGRAM_RAINBOW                 ||  \
    DEBUG_LIGHT_PROGRAM_RAW                     ||  \
    DEBUG_LIGHT_PROGRAM_REDGREENCHASE           ||  \
    DEBUG_LIGHT_PROGRAM_RANDOM_FADE             ||  \
    DEBUG_LIGHT_PROGRAM_SHOOTING_STARS          ||  \
    DEBUG_LIGHT_PROGRAM_SOLID                   ||  \
    DEBUG_LIGHT_PROGRAM_SPOOKYFLICKER           ||  \
    DEBUG_LIGHT_PROGRAM_SPOOKYSLOW              ||  \
    DEBUG_LIGHT_PROGRAM_STAR                    ||  \
    DEBUG_LIGHT_PROGRAM_STEREO                  ||  \
    DEBUG_LIGHT_PROGRAM_STOCK                   ||  \
    DEBUG_LIGHT_PROGRAM_STROBE_FILL             ||  \
    DEBUG_LIGHT_PROGRAM_TWINKLE                 ||  \
    DEBUG_LIGHT_PROGRAM_WAVE                    ||  \
    0)

#define DEBUG_CONTROLLER_ANY    (                       \
    DEBUG_CONTROLLER                                ||  \
    DEBUG_PROGRAM_RUNNER                            ||  \
    DEBUG_LIGHT_PROGRAM_CONTROLLER_HOLLY            ||  \
    DEBUG_LIGHT_PROGRAM_CONTROLLER_ICE              ||  \
    DEBUG_LIGHT_PROGRAM_CONTROLLER_CANDY_CANE       ||  \
    DEBUG_LIGHT_PROGRAM_CONTROLLER_DISSOLVE         ||  \
    DEBUG_LIGHT_PROGRAM_CONTROLLER_SOLID_RAINBOW    ||  \
    DEBUG_LIGHT_PROGRAM_CONTROLLER_METEORITE        ||  \
    DEBUG_LIGHT_PROGRAM_CONTROLLER_TWINKLE          ||  \
    DEBUG_LIGHT_PROGRAM_CONTROLLER_CHASE            ||  \
    DEBUG_LIGHT_PROGRAM_CONTROLLER_STROBE           ||  \
    DEBUG_LIGHT_PROGRAM_CONTROLLER_RAINBOW_STROBE   ||  \
    DEBUG_LIGHT_PROGRAM_CONTROLLER_RAINBOW_CHASE    ||  \
    DEBUG_LIGHT_PROGRAM_CONTROLLER_FADEIN_FADEOUT   ||  \
    DEBUG_LIGHT_PROGRAM_CONTROLLER_ALTERNATE_DIRECTION  ||  \
    DEBUG_LIGHT_PROGRAM_CONTROLLER_SPIRAL_STARS     ||  \
    DEBUG_LIGHT_PROGRAM_CONTROLLER_STEPPED_WAVE     ||  \
    DEBUG_LIGHT_PROGRAM_CONTROLLER_STROBE_FILL      ||  \
    DEBUG_LIGHT_PROGRAM_CONTROLLER_UW               ||  \
    DEBUG_LIGHT_PROGRAM_CONTROLLER_SEAHAWKS         ||  \
    0)

#endif //_DEBUG_CONFIG_H_

